; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?qInitResources_LogWatcher@@YAHXZ		; qInitResources_LogWatcher
PUBLIC	?qCleanupResources_LogWatcher@@YAHXZ		; qCleanupResources_LogWatcher
PUBLIC	?dummy@?A0x521f185c@@3Uinitializer@1@A		; `anonymous namespace'::dummy
EXTRN	atexit:PROC
_BSS	SEGMENT
?dummy@?A0x521f185c@@3Uinitializer@1@A DB 01H DUP (?)	; `anonymous namespace'::dummy
_BSS	ENDS
CRT$XCU	SEGMENT
?dummy$initializer$@?A0x521f185c@@3P6AXXZEA DQ FLAT:??__Edummy@?A0x521f185c@@YAXXZ ; `anonymous namespace'::dummy$initializer$
CRT$XCU	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??__Fdummy@?A0x521f185c@@YAXXZ
text$yd	SEGMENT
??__Fdummy@?A0x521f185c@@YAXXZ PROC			; `anonymous namespace'::`dynamic atexit destructor for 'dummy'', COMDAT
	ret	0
??__Fdummy@?A0x521f185c@@YAXXZ ENDP			; `anonymous namespace'::`dynamic atexit destructor for 'dummy''
text$yd	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??__Edummy@?A0x521f185c@@YAXXZ
text$di	SEGMENT
??__Edummy@?A0x521f185c@@YAXXZ PROC			; `anonymous namespace'::`dynamic initializer for 'dummy'', COMDAT
; File d:\builder\c++\logwatcher\64bit version\v1.3\logwatcher\logwatcher\x64\release\rcc\qrc_logwatcher.cpp
; Line 45
	lea	rcx, OFFSET FLAT:??__Fdummy@?A0x521f185c@@YAXXZ ; `anonymous namespace'::`dynamic atexit destructor for 'dummy''
	jmp	atexit
??__Edummy@?A0x521f185c@@YAXXZ ENDP			; `anonymous namespace'::`dynamic initializer for 'dummy''
text$di	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1initializer@?A0x521f185c@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1initializer@?A0x521f185c@@QEAA@XZ PROC		; `anonymous namespace'::initializer::~initializer, COMDAT
; File d:\builder\c++\logwatcher\64bit version\v1.3\logwatcher\logwatcher\x64\release\rcc\qrc_logwatcher.cpp
; Line 44
	ret	0
??1initializer@?A0x521f185c@@QEAA@XZ ENDP		; `anonymous namespace'::initializer::~initializer
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0initializer@?A0x521f185c@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0initializer@?A0x521f185c@@QEAA@XZ PROC		; `anonymous namespace'::initializer::initializer, COMDAT
; File d:\builder\c++\logwatcher\64bit version\v1.3\logwatcher\logwatcher\x64\release\rcc\qrc_logwatcher.cpp
; Line 43
	mov	rax, rcx
	ret	0
??0initializer@?A0x521f185c@@QEAA@XZ ENDP		; `anonymous namespace'::initializer::initializer
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?qCleanupResources_LogWatcher@@YAHXZ
_TEXT	SEGMENT
?qCleanupResources_LogWatcher@@YAHXZ PROC		; qCleanupResources_LogWatcher, COMDAT
; File d:\builder\c++\logwatcher\64bit version\v1.3\logwatcher\logwatcher\x64\release\rcc\qrc_logwatcher.cpp
; Line 38
	mov	eax, 1
; Line 39
	ret	0
?qCleanupResources_LogWatcher@@YAHXZ ENDP		; qCleanupResources_LogWatcher
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?qInitResources_LogWatcher@@YAHXZ
_TEXT	SEGMENT
?qInitResources_LogWatcher@@YAHXZ PROC			; qInitResources_LogWatcher, COMDAT
; File d:\builder\c++\logwatcher\64bit version\v1.3\logwatcher\logwatcher\x64\release\rcc\qrc_logwatcher.cpp
; Line 32
	mov	eax, 1
; Line 33
	ret	0
?qInitResources_LogWatcher@@YAHXZ ENDP			; qInitResources_LogWatcher
_TEXT	ENDS
END
