; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG165443 DB	'c:\qt\qt5.13.0\5.13.0\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG165444 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG165445 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG168562 DB	'c:\qt\qt5.13.0\5.13.0\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG168563 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG168564 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG168923 DB	'c:\qt\qt5.13.0\5.13.0\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG168924 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG168925 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG169284 DB	'c:\qt\qt5.13.0\5.13.0\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG169285 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG169286 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_LogWatcher__DlgEdit@@3Uqt_meta_stringdata_LogWatcher__DlgEdit_t@@B DD 0ffffffffH ; qt_meta_stringdata_LogWatcher__DlgEdit
	DD	013H
	DD	00H
	ORG $+4
	DQ	0000000000000060H
	DD	0ffffffffH
	DD	0bH
	DD	00H
	ORG $+4
	DQ	000000000000005cH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000050H
	DD	0ffffffffH
	DD	015H
	DD	00H
	ORG $+4
	DQ	0000000000000039H
	DB	04cH
	DB	06fH
	DB	067H
	DB	057H
	DB	061H
	DB	074H
	DB	063H
	DB	068H
	DB	065H
	DB	072H
	DB	03aH
	DB	03aH
	DB	044H
	DB	06cH
	DB	067H
	DB	045H
	DB	064H
	DB	069H
	DB	074H
	DB	00H
	DB	073H
	DB	069H
	DB	067H
	DB	06eH
	DB	061H
	DB	06cH
	DB	052H
	DB	065H
	DB	061H
	DB	064H
	DB	079H
	DB	00H
	DB	00H
	DB	06fH
	DB	06eH
	DB	05fH
	DB	062H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	042H
	DB	06fH
	DB	078H
	DB	05fH
	DB	061H
	DB	063H
	DB	063H
	DB	065H
	DB	070H
	DB	074H
	DB	065H
	DB	064H
	DB	00H
	ORG $+1
	ORG $+8
?qt_meta_data_LogWatcher__DlgEdit@@3QBIB DD 08H		; qt_meta_data_LogWatcher__DlgEdit
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	00H
	DD	018H
	DD	02H
	DD	06H
	DD	03H
	DD	00H
	DD	019H
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG170127 DB	'c:\qt\qt5.13.0\5.13.0\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG170128 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG170129 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG170581 DB	'c:\qt\qt5.13.0\5.13.0\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG170582 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG170583 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG170942 DB	'c:\qt\qt5.13.0\5.13.0\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG170943 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG170944 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@DlgEdit@LogWatcher@@UEBAPEBUQMetaObject@@XZ ; LogWatcher::DlgEdit::metaObject
PUBLIC	?qt_metacast@DlgEdit@LogWatcher@@UEAAPEAXPEBD@Z	; LogWatcher::DlgEdit::qt_metacast
PUBLIC	?qt_metacall@DlgEdit@LogWatcher@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; LogWatcher::DlgEdit::qt_metacall
PUBLIC	?qt_static_metacall@DlgEdit@LogWatcher@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; LogWatcher::DlgEdit::qt_static_metacall
PUBLIC	?signalReady@DlgEdit@LogWatcher@@QEAAXXZ	; LogWatcher::DlgEdit::signalReady
PUBLIC	?staticMetaObject@DlgEdit@LogWatcher@@2UQMetaObject@@B ; LogWatcher::DlgEdit::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QDialog@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?on_buttonBox_accepted@DlgEdit@LogWatcher@@AEAAXXZ:PROC ; LogWatcher::DlgEdit::on_buttonBox_accepted
EXTRN	__imp_?staticMetaObject@QDialog@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@DlgEdit@LogWatcher@@2UQMetaObject@@B DB 030H DUP (?) ; LogWatcher::DlgEdit::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@DlgEdit@LogWatcher@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@DlgEdit@LogWatcher@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@DlgEdit@LogWatcher@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@DlgEdit@LogWatcher@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@DlgEdit@LogWatcher@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@DlgEdit@LogWatcher@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@DlgEdit@LogWatcher@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN15
	DD	imagerel $LN15+265
	DD	imagerel $unwind$?qt_static_metacall@DlgEdit@LogWatcher@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?signalReady@DlgEdit@LogWatcher@@QEAAXXZ DD imagerel $LN3
	DD	imagerel $LN3+38
	DD	imagerel $unwind$?signalReady@DlgEdit@LogWatcher@@QEAAXXZ
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@DlgEdit@LogWatcher@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@DlgEdit@LogWatcher@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@DlgEdit@LogWatcher@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@DlgEdit@LogWatcher@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@DlgEdit@LogWatcher@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@DlgEdit@LogWatcher@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@DlgEdit@LogWatcher@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	0a217H
$unwind$?signalReady@DlgEdit@LogWatcher@@QEAAXXZ DD 010901H
	DD	04209H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@DlgEdit@LogWatcher@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@DlgEdit@LogWatcher@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'LogWatcher::DlgEdit::staticMetaObject'', COMDAT
; File d:\builder\c++\logwatcher\64bit version\v1.6\logwatcher\logwatcher\x64\debug\moc\moc_dlgedit.cpp
; Line 98
	mov	rax, QWORD PTR __imp_?staticMetaObject@QDialog@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@DlgEdit@LogWatcher@@2UQMetaObject@@B, rax
; Line 99
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_LogWatcher__DlgEdit@@3Uqt_meta_stringdata_LogWatcher__DlgEdit_t@@B
	mov	QWORD PTR ?staticMetaObject@DlgEdit@LogWatcher@@2UQMetaObject@@B+8, rax
; Line 100
	lea	rax, OFFSET FLAT:?qt_meta_data_LogWatcher__DlgEdit@@3QBIB
	mov	QWORD PTR ?staticMetaObject@DlgEdit@LogWatcher@@2UQMetaObject@@B+16, rax
; Line 101
	lea	rax, OFFSET FLAT:?qt_static_metacall@DlgEdit@LogWatcher@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; LogWatcher::DlgEdit::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@DlgEdit@LogWatcher@@2UQMetaObject@@B+24, rax
; Line 102
	mov	QWORD PTR ?staticMetaObject@DlgEdit@LogWatcher@@2UQMetaObject@@B+32, 0
; Line 103
	mov	QWORD PTR ?staticMetaObject@DlgEdit@LogWatcher@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@DlgEdit@LogWatcher@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'LogWatcher::DlgEdit::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
?signalReady@DlgEdit@LogWatcher@@QEAAXXZ PROC		; LogWatcher::DlgEdit::signalReady
; File d:\builder\c++\logwatcher\64bit version\v1.6\logwatcher\logwatcher\x64\debug\moc\moc_dlgedit.cpp
; Line 139
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 140
	xor	r9d, r9d
	xor	r8d, r8d
	lea	rdx, OFFSET FLAT:?staticMetaObject@DlgEdit@LogWatcher@@2UQMetaObject@@B ; LogWatcher::DlgEdit::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 141
	add	rsp, 40					; 00000028H
	ret	0
?signalReady@DlgEdit@LogWatcher@@QEAAXXZ ENDP		; LogWatcher::DlgEdit::signalReady
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
tv89 = 36
_t$1 = 40
result$2 = 48
$T3 = 56
_o$ = 96
_c$ = 104
_id$ = 112
_a$ = 120
?qt_static_metacall@DlgEdit@LogWatcher@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; LogWatcher::DlgEdit::qt_static_metacall
; File d:\builder\c++\logwatcher\64bit version\v1.6\logwatcher\logwatcher\x64\debug\moc\moc_dlgedit.cpp
; Line 75
$LN15:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 88					; 00000058H
; Line 76
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 77
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 79
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN7@qt_static_
	jmp	SHORT $LN8@qt_static_
$LN6@qt_static_:
; Line 80
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?signalReady@DlgEdit@LogWatcher@@QEAAXXZ ; LogWatcher::DlgEdit::signalReady
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 81
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?on_buttonBox_accepted@DlgEdit@LogWatcher@@AEAAXXZ ; LogWatcher::DlgEdit::on_buttonBox_accepted
$LN8@qt_static_:
$LN2@qt_static_:
; Line 84
	jmp	$LN5@qt_static_
$LN4@qt_static_:
	cmp	DWORD PTR _c$[rsp], 10
	jne	$LN9@qt_static_
; Line 85
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	QWORD PTR result$2[rsp], rax
; Line 88
	lea	rax, OFFSET FLAT:?signalReady@DlgEdit@LogWatcher@@QEAAXXZ ; LogWatcher::DlgEdit::signalReady
	mov	QWORD PTR $T3[rsp], rax
	mov	DWORD PTR $T3[rsp+8], 0
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T3[rsp]
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN13@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	cmp	QWORD PTR [rax], 0
	je	SHORT $LN12@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, DWORD PTR $T3[rsp+8]
	cmp	DWORD PTR [rax+8], ecx
	jne	SHORT $LN13@qt_static_
$LN12@qt_static_:
	mov	DWORD PTR tv89[rsp], 1
	jmp	SHORT $LN14@qt_static_
$LN13@qt_static_:
	mov	DWORD PTR tv89[rsp], 0
$LN14@qt_static_:
	cmp	DWORD PTR tv89[rsp], 0
	je	SHORT $LN10@qt_static_
; Line 89
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 0
$LN10@qt_static_:
$LN9@qt_static_:
$LN5@qt_static_:
; Line 95
	add	rsp, 88					; 00000058H
	ret	0
?qt_static_metacall@DlgEdit@LogWatcher@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; LogWatcher::DlgEdit::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@DlgEdit@LogWatcher@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; LogWatcher::DlgEdit::qt_metacall
; File d:\builder\c++\logwatcher\64bit version\v1.6\logwatcher\logwatcher\x64\debug\moc\moc_dlgedit.cpp
; Line 121
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 122
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 123
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 124
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 125
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 126
	cmp	DWORD PTR _id$[rsp], 2
	jge	SHORT $LN5@qt_metacal
; Line 127
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@DlgEdit@LogWatcher@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; LogWatcher::DlgEdit::qt_static_metacall
$LN5@qt_metacal:
; Line 128
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 2
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 129
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 130
	cmp	DWORD PTR _id$[rsp], 2
	jge	SHORT $LN7@qt_metacal
; Line 131
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 132
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 2
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 134
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 135
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@DlgEdit@LogWatcher@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; LogWatcher::DlgEdit::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@DlgEdit@LogWatcher@@UEAAPEAXPEBD@Z PROC	; LogWatcher::DlgEdit::qt_metacast
; File d:\builder\c++\logwatcher\64bit version\v1.6\logwatcher\logwatcher\x64\debug\moc\moc_dlgedit.cpp
; Line 113
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 114
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 115
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_LogWatcher__DlgEdit@@3Uqt_meta_stringdata_LogWatcher__DlgEdit_t@@B+96
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 116
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 117
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QDialog@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 118
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@DlgEdit@LogWatcher@@UEAAPEAXPEBD@Z ENDP	; LogWatcher::DlgEdit::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@DlgEdit@LogWatcher@@UEBAPEBUQMetaObject@@XZ PROC ; LogWatcher::DlgEdit::metaObject
; File d:\builder\c++\logwatcher\64bit version\v1.6\logwatcher\logwatcher\x64\debug\moc\moc_dlgedit.cpp
; Line 108
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 109
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@DlgEdit@LogWatcher@@2UQMetaObject@@B ; LogWatcher::DlgEdit::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 110
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@DlgEdit@LogWatcher@@UEBAPEBUQMetaObject@@XZ ENDP ; LogWatcher::DlgEdit::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\qt\qt5.13.0\5.13.0\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File d:\builder\c++\logwatcher\64bit version\v1.6\logwatcher\logwatcher\x64\debug\moc\moc_dlgedit.cpp
; Line 144
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File d:\builder\c++\logwatcher\64bit version\v1.6\logwatcher\logwatcher\x64\debug\moc\moc_dlgedit.cpp
; Line 144
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
